# kaggle https://kaggle.com

<데이터셋의 변수들>

Country: 모두 알다시피 나라입니다... 해당 기관에선 총 149개국을 조사했네요. (row가 149개겠죠?)

Regional_indicator: 세계의 대표적인 지역 10개로 묶어놓은 범주형 변수입니다 (동아시아, 서유럽 등등...)

Ladder_score: 각 국가의 국민들에게 전반적인 행복지수에 대한 설문을 진행해서 나온 점수입니다.
(0~10점, 높을 수록 행복함)

Logged_GDP_per_capita: 모두가 한번쯤 들어보셨을 GDP입니다! 다른 변수들과 scale 차이가 크다보니 해당 데이터에선 로그를 씌워서 최대 11,12 정도가 되게 해놨네요.

Social_support: '문제가 생겼을 때 언제든지 도와줄 수 있는 사람이 있나요?' 에 대한 답을 Yes는 1, No는 0으로 하여 얻은 국가별 평균값입니다.

Healthy_life_expectancy: 각 나라의 기대 수명입니다.

Freedom_to make_life_choices: '본인이 하려던 것에 주어진 자유에 만족하나요?'에 대한 답변을 통해 얻은 평균입니다.

Generosity: '지난 달에 기부를 한적이 있나요?'에 대한 대답과 GDP를 회귀 분석하여 나온 residual 값입니다.

Pereception_of_corruption: '정부에 부정, 부패가 만연한가요?', '직장에 부정, 부패가 만연한가요?' 에 대한 답변을 통해 얻은 평균입니다.

In [1]:
import pandas as pd
df = pd.read_csv('./world-happiness-report-2021.csv')
df

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.000,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.700,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.400,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
3,Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.000,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
4,Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.400,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,Lesotho,Sub-Saharan Africa,3.512,0.120,3.748,3.276,7.926,0.787,48.700,0.715,-0.131,0.915,2.43,0.451,0.731,0.007,0.405,0.103,0.015,1.800
145,Botswana,Sub-Saharan Africa,3.467,0.074,3.611,3.322,9.782,0.784,59.269,0.824,-0.246,0.801,2.43,1.099,0.724,0.340,0.539,0.027,0.088,0.648
146,Rwanda,Sub-Saharan Africa,3.415,0.068,3.548,3.282,7.676,0.552,61.400,0.897,0.061,0.167,2.43,0.364,0.202,0.407,0.627,0.227,0.493,1.095
147,Zimbabwe,Sub-Saharan Africa,3.145,0.058,3.259,3.030,7.943,0.750,56.201,0.677,-0.047,0.821,2.43,0.457,0.649,0.243,0.359,0.157,0.075,1.205
148,Afghanistan,South Asia,2.523,0.038,2.596,2.449,7.695,0.463,52.493,0.382,-0.102,0.924,2.43,0.370,0.000,0.126,0.000,0.122,0.010,1.895

In [9]:
df['Country name'].str.extract(r'(^.{5})')

         0
0    Finla
1    Denma
2    Switz
3    Icela
4    Nethe
..     ...
144  Lesot
145  Botsw
146  Rwand
147  Zimba
148  Afgha

[149 rows x 1 columns]

In [10]:
import numpy as np
df['first_five_letter'] = df['Country name'].str.extract(r'(^.{5})')
df.head()

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,...,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,first_five_letter
0,Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.0,0.949,...,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253,Finla
1,Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.7,0.946,...,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868,Denma
2,Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.4,0.919,...,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839,Switz
3,Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.0,0.955,...,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967,Icela
4,Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.4,0.913,...,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798,Nethe

# Pandas Count

In [17]:
S = pd.Series(['Finland', 'Colombia', 'Florida', 'Japan', 'Puerto Rico', 'Russia', 'france'])
S[S.str.count(r'(^F.*)') == 1]
# S.str.count(r'^F.*')

0    Finland
2    Florida
dtype: object

In [18]:
# 결론은 어떤 값을 찾는 다는 것은, True 와 False 의 Series 를 주면 되는 것.
df['Country name'].str.count('^[pP]') > 0

0      False
1      False
2      False
3      False
4      False
       ...
144    False
145    False
146    False
147    False
148    False
Name: Country name, Length: 149, dtype: bool

In [19]:
df[ df['Country name'].str.count('^[pP]') > 0 ]

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,...,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,first_five_letter
40,Panama,Latin America and Caribbean,6.180,0.073,6.323,6.036,10.350,0.896,69.652,0.872,...,0.856,2.43,1.298,0.976,0.667,0.596,0.079,0.053,2.509,Panam
43,Poland,Central and Eastern Europe,6.166,0.040,6.245,6.087,10.382,0.898,69.702,0.841,...,0.735,2.43,1.309,0.982,0.668,0.558,0.080,0.130,2.438,Polan
57,Portugal,Western Europe,5.929,0.055,6.037,5.821,10.421,0.879,72.600,0.892,...,0.887,2.43,1.323,0.939,0.760,0.621,0.029,0.033,2.225,Portu
60,Philippines,Southeast Asia,5.880,0.052,5.982,5.778,9.076,0.830,62.000,0.917,...,0.742,2.43,0.853,0.828,0.426,0.651,0.125,0.126,2.872,Phili
62,Peru,Latin America and Caribbean,5.840,0.075,5.988,5.692,9.458,0.832,68.250,0.822,...,0.891,2.43,0.986,0.833,0.623,0.536,0.087,0.031,2.744,NaN
70,Paraguay,Latin America and Caribbean,5.653,0.092,5.832,5.473,9.448,0.893,65.900,0.876,...,0.882,2.43,0.983,0.970,0.549,0.602,0.206,0.037,2.306,Parag
104,Pakistan,South Asia,4.934,0.068,5.066,4.802,8.458,0.651,58.709,0.726,...,0.787,2.43,0.637,0.423,0.322,0.418,0.252,0.097,2.784,Pakis
124,Palestinian Territories,Middle East and North Africa,4.517,0.067,4.649,4.384,8.485,0.826,62.250,0.653,...,0.821,2.43,0.646,0.819,0.434,0.330,0.082,0.075,2.131,Pales

# Pandas Match

In [21]:
S = pd.Series(['Finland', 'Colombia', 'Florida', 'Japan', 'Puerto Rico', 'Russia', 'france'])
S.str.match(r'^P.*') # 그냥 true false value 임.

0    False
1    False
2    False
3    False
4     True
5    False
6    False
dtype: bool

In [23]:
# 위와 동일하지 않을까? ==> 역시 동일해.
S.str.match(r'^P.*') == True

0    False
1    False
2    False
3    False
4     True
5    False
6    False
dtype: bool

In [32]:
df[df['Country name'].str.match('.*[kK][oO]')]

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,...,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,first_five_letter
32,Kosovo,Central and Eastern Europe,6.372,0.059,6.487,6.257,9.318,0.821,63.813,0.869,...,0.917,2.43,0.937,0.807,0.483,0.593,0.356,0.014,3.182,Kosov
61,South Korea,East Asia,5.845,0.042,5.928,5.763,10.651,0.799,73.900,0.672,...,0.727,2.43,1.403,0.758,0.801,0.353,0.134,0.135,2.262,South
76,Hong Kong S.A.R. of China,East Asia,5.477,0.049,5.573,5.380,11.000,0.836,76.820,0.717,...,0.403,2.43,1.525,0.841,0.893,0.408,0.232,0.342,1.236,Hong

# Pandas Replace

In [33]:
# Remove the dash(-) followed by number from all countries in the Series
S=pd.Series(['Finland-1','Colombia-2','Florida-3','Japan-4','Puerto Rico-5','Russia-6','france_7'])
S.replace('-\d', '', regex=True, inplace=True)
S

0        Finland
1       Colombia
2        Florida
3          Japan
4    Puerto Rico
5         Russia
6       france_7
dtype: object

> 문자 더하기 되나?

In [34]:
df2 = df.copy()
df2

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,...,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,first_five_letter
0,Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.000,0.949,...,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253,Finla
1,Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.700,0.946,...,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868,Denma
2,Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.400,0.919,...,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839,Switz
3,Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.000,0.955,...,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967,Icela
4,Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.400,0.913,...,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798,Nethe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,Lesotho,Sub-Saharan Africa,3.512,0.120,3.748,3.276,7.926,0.787,48.700,0.715,...,0.915,2.43,0.451,0.731,0.007,0.405,0.103,0.015,1.800,Lesot
145,Botswana,Sub-Saharan Africa,3.467,0.074,3.611,3.322,9.782,0.784,59.269,0.824,...,0.801,2.43,1.099,0.724,0.340,0.539,0.027,0.088,0.648,Botsw
146,Rwanda,Sub-Saharan Africa,3.415,0.068,3.548,3.282,7.676,0.552,61.400,0.897,...,0.167,2.43,0.364,0.202,0.407,0.627,0.227,0.493,1.095,Rwand
147,Zimbabwe,Sub-Saharan Africa,3.145,0.058,3.259,3.030,7.943,0.750,56.201,0.677,...,0.821,2.43,0.457,0.649,0.243,0.359,0.157,0.075,1.205,Zimba
148,Afghanistan,South Asia,2.523,0.038,2.596,2.449,7.695,0.463,52.493,0.382,...,0.924,2.43,0.370,0.000,0.126,0.000,0.122,0.010,1.895,Afgha

In [35]:
df2.columns[:2]

Index(['Country name', 'Regional indicator'], dtype='object')

In [36]:
df2.rename(columns = {'Country name': 'country_name'}, inplace=True)

In [38]:
df2.rename(columns = {'Regional indicator': 'region'}, inplace=True)
df2.columns[:2]

Index(['country_name', 'region'], dtype='object')

In [41]:
df2.eval('my_loc = country_name + "__" + region')
# 음. 역시 두개의 문자를 합치는 것은 힘들군.

TypeError: unsupported operand type(s) for +: 'object' and '<class 'str'>'

In [46]:
df2['my_loc'] = df2.apply(lambda row: row['country_name'] + '__' + row['region'], axis=1)

In [54]:
df2.loc[:,['my_loc','country_name','region']]

                           my_loc country_name              region
0         Finland__Western Europe      Finland      Western Europe
1         Denmark__Western Europe      Denmark      Western Europe
2     Switzerland__Western Europe  Switzerland      Western Europe
3         Iceland__Western Europe      Iceland      Western Europe
4     Netherlands__Western Europe  Netherlands      Western Europe
..                            ...          ...                 ...
144   Lesotho__Sub-Saharan Africa      Lesotho  Sub-Saharan Africa
145  Botswana__Sub-Saharan Africa     Botswana  Sub-Saharan Africa
146    Rwanda__Sub-Saharan Africa       Rwanda  Sub-Saharan Africa
147  Zimbabwe__Sub-Saharan Africa     Zimbabwe  Sub-Saharan Africa
148       Afghanistan__South Asia  Afghanistan          South Asia

[149 rows x 3 columns]

In [52]:
df2['country_name'].str.match('^.*[sS][oO]').sum()

5

In [55]:
df3 = df2.loc[:,['my_loc','country_name','region']].copy()

In [56]:
df3.loc[df3['country_name'].str.match(r'.*[sS][oO]'),'FLAG'] = 'KOREA?'

In [57]:
df3[df3['FLAG'] == 'KOREA?']

,my_loc,country_name,region,FLAG
32,Kosovo__Central and Eastern Europe,Kosovo,Central and Eastern Europe,KOREA?
61,South Korea__East Asia,South Korea,East Asia,KOREA?
102,South Africa__Sub-Saharan Africa,South Africa,Sub-Saharan Africa,KOREA?
112,Burkina Faso__Sub-Saharan Africa,Burkina Faso,Sub-Saharan Africa,KOREA?
144,Lesotho__Sub-Saharan Africa,Lesotho,Sub-Saharan Africa,KOREA?

In [59]:
df3[df3['country_name'].str.match(r'^South')]['my_loc']

61               South Korea__East Asia
102    South Africa__Sub-Saharan Africa
Name: my_loc, dtype: object